### ISSUE TITLE
pip3 install can't find STARE.h

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/pystare#1]
I am working on building the code. I figured out that I need swig, and there are some other issues I’ve found. Once that was done, running 'pip3 install --editable /Users/jimg/src/opendap/pystare’ fails:

[nori:pystare jimg$] pip3 install --editable /Users/jimg/src/opendap/pystare
Obtaining file:///Users/jimg/src/opendap/pystare
Requirement already satisfied: numpy>=1.16.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pystare==0.2.0) (1.18.2)
Requirement already satisfied: shapely>=1.6 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pystare==0.2.0) (1.7.0)
Requirement already satisfied: geopandas>=0.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pystare==0.2.0) (0.7.0)
Requirement already satisfied: pyproj>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from geopandas>=0.5->pystare==0.2.0) (2.6.0)
Requirement already satisfied: pandas>=0.23.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from geopandas>=0.5->pystare==0.2.0) (1.0.3)
Requirement already satisfied: fiona in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from geopandas>=0.5->pystare==0.2.0) (1.8.13.post1)
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas>=0.23.0->geopandas>=0.5->pystare==0.2.0) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas>=0.23.0->geopandas>=0.5->pystare==0.2.0) (2.8.1)
Requirement already satisfied: click-plugins>=1.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from fiona->geopandas>=0.5->pystare==0.2.0) (1.1.1)
Requirement already satisfied: munch in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from fiona->geopandas>=0.5->pystare==0.2.0) (2.5.0)
Requirement already satisfied: six>=1.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from fiona->geopandas>=0.5->pystare==0.2.0) (1.14.0)
Requirement already satisfied: cligj>=0.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from fiona->geopandas>=0.5->pystare==0.2.0) (0.5.0)
Requirement already satisfied: attrs>=17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from fiona->geopandas>=0.5->pystare==0.2.0) (19.3.0)
Requirement already satisfied: click<8,>=4.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from fiona->geopandas>=0.5->pystare==0.2.0) (7.1.1)
Installing collected packages: pystare
  Running setup.py develop for pystare
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c "import setuptools, tokenize;__file__='/Users/jimg/src/opendap/pystare/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing pystare.egg-info/PKG-INFO
    writing dependency_links to pystare.egg-info/dependency_links.txt
    writing requirements to pystare.egg-info/requires.txt
    writing top-level names to pystare.egg-info/top_level.txt
    file pystare.py (for module pystare) not found
    reading manifest file 'pystare.egg-info/SOURCES.txt'
    writing manifest file 'pystare.egg-info/SOURCES.txt'
    running build_ext
    building '_pystare' extension
    swigging PySTARE.i to PySTARE_wrap.cpp
    swig -python -modern -c++ -o PySTARE_wrap.cpp PySTARE.i
    Deprecated command line option: -modern. This option is now always on.
    creating build
    creating build/temp.macosx-10.9-x86_64-3.7
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c PySTARE_wrap.cpp -o build/temp.macosx-10.9-x86_64-3.7/PySTARE_wrap.o -std=c++11
    In file included from PySTARE_wrap.cpp:2774:
    ./PySTARE.h:25:10: fatal error: 'STARE.h' file not found
    #include "STARE.h"
             ^~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
----------------------------------------

Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c "import setuptools, tokenize;__file__='/Users/jimg/src/opendap/pystare/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/jimg/src/opendap/pystare/
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[nori:pystare jimg$] 

Yet I set the env vars. I have some fires to put out in another project, but I’ll work for the bulk of today on STARE and the python code. No worries about the docs…

**Comment by jgallagher59701** [comment]
I figure this out - I was using the wrong name for the STARE_INCLUDE_DIR env var. I changed to that name and the build worked.

**Comment by jgallagher59701** [comment]
I would close this.
