### ISSUE TITLE
What's the new version of ps.from_polygon?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/pystare#105]
I'm trying to update the following code.

```
covers = covers + [ps.from_polygon(shapely.geometry.Polygon(lines[k]),resolution=cover_resolution
                                       ,nonconvex=False)]
```

**Comment by NiklasPhabian** [comment]
We don't treat polygons in pystare. Only rings and hulls. (Polygons are made up of one exterior ring and zero or more interior rings). We do treat polygons in starepandas. To lookup covers from hulls or rings use: ```cover_from_hull``` or ```cover_from_ring```.

**Comment by michaelleerilee** [comment]
[The manual entry for STAREPandas and shapely polygons.](https://starepandas.readthedocs.io/en/latest/docs/reference/api/starepandas.tools.spatial_conversions.sids_from_polygon.html#starepandas.tools.spatial_conversions.sids_from_polygon)
