### ISSUE TITLE
Feature request: Collapse collection of STARE IDs

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#17]
We talked about the performance of creating STARE covers of granules in the past. 
- If we are lucky, a granule contains g-ring information (4 lat/lon pairs) and we can construct the STARE cover from those
- If we are unlucky, the granule doesn't. We then can either choose to:
a) use the 4 corner points of the lat/lon array and pretend those form a g-ring and construct STARE cover from those.
b) construct a (non-g) ring/polygon from the edges of the lat/lon array

a) is technically incorrect, b) is expensive. Further, I wonder if those approaches even make sense for the xcal microwave products with conical scanning.

Could we imagine a 3rd way where we take the collection of SIDs of each iFOV of a granule and attempt to collapse those into the cover? I would imagine that whenever we find 4 child SIDs with the same parent, we replace them with the parent. But there are probably more efficient ways of doing this.

**Comment by michaelleerilee** [comment]
Since you put this in pystare, is the pystare.srange the sort of thing you're looking for as a 3rd way? Cf. https://github.com/SpatioTemporal/STARE-Cookbooks/blob/master/contrib/jupyter/03-SpatialRange.ipynb

**Comment by michaelleerilee** [comment]
The big cost (for now) is the conversion from lon-lat to STARE id. Since this has to be done anyway for the STAREmaster lookup tables, we just need to make sure we don't unnecessarily recalculate.

**Comment by michaelleerilee** [comment]
Regarding (conical) scan geometries, we should consider the notion of a scan as an object/type, which is implicit in the semantics of some of these granule files.

Also, there's a range of non-g polygons you can get by changing the stride around a granule geolocation array. "4-corner points" is one end of the range, "every point on edge of array" is the other. In one of my STAREmaster branches I added C++ code to perform this sort of striding.

**Comment by NiklasPhabian** [comment]
> is the pystare.srange the sort of thing you're looking for?
I think it might be. I am trying this out right now. 

> Since this has to be done anyway for the STAREmaster lookup tables, we just need to make sure we don't unnecessarily recalculate.
I agree, but this is not just about compute time, but also about how quickly one can add support to new products. Not dealing with the GRINGs/edges/corners and optimizing stride probably would save 50 % of the effort.

**Comment by NiklasPhabian** [comment]
![ssmis](https://user-images.githubusercontent.com/6323307/108243001-d27dbf00-710a-11eb-9b00-888e3e937118.png]

**Comment by NiklasPhabian** [comment]
as discussed, spatial ranges should be able to eat e.g. 4 sibling SIDs with the same parent and allow us to extract the parent SID. This does not work as of now. Tests are in:
3d4483bb42638561f978399a070ad69302654c76

**Comment by michaelleerilee** [comment]
There is a low level "compress" function in STARE, which has not been exposed but which is available via intersection. This is why the trixel coalescence has been seen in some uses of pystare.srange and not others. We'll add this to STARE's SpatialRange and then expose through pystare.

**Comment by michaelleerilee** [comment]
Note: Kuo has recommended the term economy_cover for a multi-resolution cover.

**Comment by NiklasPhabian** [comment]
huh. Hasn't this been solved for a while now?
We can do

```python 
sids = numpy.unique(sids)
s_range = pystare.to_compressed_range(sids)
expanded = pystare.expand_intervals(s_range, -1, multi_resolution=True)
```
