### ISSUE TITLE
_to_vertices_latlon() and to_vertices_latlon() 

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#19]
Leading underscores are to be understood as private functions. Actually privacy does not exist in python. It is really just a coding convention 
https://docs.python.org/2/tutorial/classes.html#private-variables-and-class-local-references

We followed this convention quite nicely in the beginning where we had private functions that were not meant to be exposed to the API. This changed when we started getting a bit more intimate with SWIG and introduced more elaborate typemaps. Before we introduced elaborate typemaps, our SWIG functions had no return values. We therefore wraped those functions in python functions to make them pythonic. The SWIG function would have the same name as the wrapper function plus leading underscore.

_to_vertices_latlon() and to_vertices_latlon() might both be legitimate functions we want to expose to the API

**Comment by michaelleerilee** [comment]
What's the call to action? This is for the pystare API, yes? Is this a matter of documentation?

**Comment by NiklasPhabian** [comment]
we should decide if _to_vertices_latlon() is a public function or not. 
If yes, we should add a public alias for it. 
Next version, we may consider renaming the function to reduce confusion between the two functions.

In general, the call for action probably is to be double careful with function naming in the future in order to create an intuitive API
