### ISSUE TITLE
temporal from/to tai_iso_strings() parameterization

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#39]
the pystare temporal conversion functions should primarily eat datetetime.datetime and numpy.datetime64 objects. We should not touch any conversion between those objects and string representations. They are well handled by those libraries. 

I think the necessity to approach it this way becomes quite explicit if a naive user (me) falis tying to do the following:

```python
import datetime
import pystare

iso_string = datetime.datetime.now().isoformat()
tid = pystare.from_tai_iso_strings(iso_string)
```

But has to do the following instead:
```python
import datetime
import pystare

iso_string = datetime.datetime.now().isoformat()[0:-3]
tid = pystare.from_tai_iso_strings([iso_string])
```

If we feed datatime objects to pystare, we cannot encapsulate the temporal resolutions in the string.  Consequently, we need to pass the resolutions as additional parameters to the conversion functions.

Aside from this, we may choose to *also* use our own hand-rolled string representation of the form ``` "2003-02-13T12:00:00.000 (12 12) (1)" ```. Though we should be very careful to not call those iso strings.

A function of the form

```python
def make_stare_time_string(datetime, forward_bound, backwards_bound):
    ...
    return stare_time_string 
``` 
should do the trick for now. 

This affects: 
```from_tai_iso_strings()```
and
```to_tai_iso_strings()```

**Comment by michaelleerilee** [comment]
Note: We should be wary of datetime UTC and TAI conversions.

**Comment by NiklasPhabian** [comment]
but I would argue that this is the users issue. 
Datetime.datetime does not care if the user enters a TAI or a UTC time. 
Datetime.datetime only holds the time representation. The TAI and UTC difference would only become relevant if the user adds or subtracts datetime.timedeltas. I would think that  timedeltas are only UTC.

**Comment by michaelleerilee** [comment]
"pystare temporal conversion functions should primarily eat datetetime.datetime and numpy.datetime64" - This is okay.

"Datetime.datetime does not care if the user enters a TAI or a UTC time." - This is bad as pystare must care. We can handle this with appropriate API functions.

"Datetime.datetime only holds the time representation. The TAI and UTC difference [is not relevant]" - Users will want to handle deltas, but I don't think it's clear from the current API how to do that. For most indexing needs the difference between UTC and TAI deltas will not be interesting.

**Comment by michaelleerilee** [comment]
This line of discussion also raises the question of how the data is stored in the actual data files themselves. Usually in floating point days or seconds since some epoch if I recall correctly.

**Comment by NiklasPhabian** [comment]
> This is bad as pystare must care. We can handle this with appropriate API functions.
I agree. Datetime is naive to UTC/TAI. We would need the user to specify if the datetime object was UTC or TAI. Either by invoking an additional parameter or (like it is right now) by using the appropriate function (from_UTC vs from_TAI)

**Comment by NiklasPhabian** [comment]
> This line of discussion also raises the question of how the data is stored in the actual data files themselves. Usually in floating point days or seconds since some epoch if I recall correctly.

In the data we have been working with so far? It varies ...

* The XCAL data has the calendrical values as separate variables. 
* MODIS has the date and the time as separate strings in the CoreMetaData dataset 
* VIIRS has ISO8601 strings as global attributes
* Landsat has separate int for ephermis epoch year and day, and a float for epoch seconds

Single floats since epoch seem  uncommon

**Comment by michaelleerilee** [comment]
I think there's usually a more amenable time variable type than string. I'll have to come back to this.

**Comment by NiklasPhabian** [comment]
> Datetime.datetime does not care if the user enters a TAI or a UTC time.
> Datetime.datetime only holds the time representation. The TAI and UTC difference would only become relevant if the user adds or subtracts datetime.timedeltas. I would think that timedeltas are only UTC.

Argh. Of course, there is also ambiguity in the leap second when a point in time is referenced with UTC.
