### ISSUE TITLE
need disambiguation for "Julian" (documentation)

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#42]
We have the set of functions:```to/from_JulianTAI/UTC()```. From a quick google search, "Julian" may not be completely unambiguous. Firstly, I think it is mainly understood as an ordinal *integer* day count. However, there might be three different "opinions" of where 1 is:

1. 1st of January of any given year ( "Julian date" or JD, or JDATE)
1. 2nd of January of any given year (e "Julian date" or JD, or JDATE)
1. January 1, 4713 BC, 
1. November 24, 4714 BC

We seem to interpret Julian as the fractional (*double*) day since January 1, 4713 BC.
This is all fine, but we have to document.

**Comment by michaelleerilee** [comment]
Yes, this should be documented.

We should look at the conventions used by https://github.com/liberfa/pyerfa . The STARE uses the ERFA Julian Day routines which uses two doubles.

**Comment by NiklasPhabian** [comment]
those folks live in their own world of conventions. 

Do they represent time with two doubles because a single double would have insufficient precision for astronomy?

"
2) The Julian Date is apportioned in any convenient way between the arguments dj1 and dj2.  For example, JD=2450123.7 could  be expressed in any of these ways, among others:

          dj1             dj2

       2450123.7           0.0       (JD method)
       2451545.0       -1421.3       (J2000 method)
       2400000.5       50123.2       (MJD method)
       2450123.5           0.2       (date & time method)
"

**Comment by michaelleerilee** [comment]
The needs of astrometry, geodesy, and astrodynamics differ from the usual computational riffraff. Don't forget "astronomy" comes into our spacecraft-based remote sensing. All of our spacecraft observation times are TAI. Numerical precision of the underlying algorithms is the main reason for the 2-doubles approach. While the epoch+offset is common, particularly in the days of printed tables.
