### ISSUE TITLE
we should not bother with conversions to/from_julian

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#43]
```datetime.datetime``` and ```numpy.datetime64``` give us all the power we need to convert between datetime representations. 

Inversely, it is actually quite a task to construct a fractional julian day count from a datetime.datetime object. I'd probably do something like that:

```python
now = datetime.datetime.now()
fractional_julian = now.toordinal() 
                          + now.hour/24 
                          + now.minute/24/60 
                          + now.second/24/60/60
```
but would be surprised if this was correct.

**Comment by michaelleerilee** [comment]
Maybe reference https://github.com/liberfa/pyerfa

**Comment by michaelleerilee** [comment]
Does datetime do TAI?

**Comment by michaelleerilee** [comment]
STARE ships with a version of https://github.com/liberfa/erfa

**Comment by NiklasPhabian** [comment]
yes. probably pyerfa would do the trick and we should use it under the hood. But I don't think we should (primarily) expose the users to the fractional julian days

**Comment by NiklasPhabian** [comment]
Alright. I guess one can construct what we need with erfa.
Note that the (not-so-explanatory) function called ```dtf2d()``` returns a tuple of two doubles. Our ```from_JulianTAI/UTC()``` eat two numpy arrays though. Therefore a bit of cumbersomeness.

``` python
import erfa
import datetime
import pystare

time_stamp = datetime.datetime(2021,2,1,12,0)
time_tuple = time_stamp.timetuple()

erfa_time = erfa.dtf2d("UTC", *time_tuple[0:6])
pystare.from_JulianTAI(numpy.array([erfa_time[0]]), numpy.array([erfa_time[1]])) 

```

**Comment by michaelleerilee** [comment]
I'd prefer not to require end-users to go to ERFA, since we already have ERFA under the hood.  (Maybe we can use ERFA to test our code in places.) 

I like what you've been saying about smoothing out the edges.

Do we need to convert datetimes to JDs?

**Comment by NiklasPhabian** [comment]
I am increasingly thinking that we should allow users to interact with STARE in any format of their choosing. We should use astropy as the pivoting object as It converts between JD and any other format. 
@michaelleerilee, what I don't understand is what our preferred point of entry into STARE is? Should STARE be eating "STARE timestrings``` (iso + resolutions + type), or should it eat two-part julian dates + resolutions + type?

I am not sure if I understand the dualism of fromJulianDateTAI/UTC() vs from_tai_iso_strings(). Only the latter lets me feed the resolutions and the type, but the two-part JDs seem more canonical. 

We should leave the parsing between "STARE timestrings" and ... well ... anything else as separate functions (and possibly leave them in python/pystare world for simplicity. Though I understand that you needed them in STARE for verification etc).

**Comment by michaelleerilee** [comment]
What do you mean by separate functions? You mean to not have them in the STARE API? JD only? POSIX only?

1. Historically, the 2-doubles calls map to ERFA calls and don't touch resolution or type, i.e. they are low-level constructor aids. **I'll try to add res/res/type to the signature.**
2. Also, the most common use case I've had so far is (A) Generate the TID, then (B) set the resolutions afterwards. Type is assumed 1 for the time being (others not implemented).
3. I don't think users working in double should have to go through an extra encoding to get a tid.
4. strings are human readable.
5. Since this is Python-world, I imagine most temporal data is going in via datetime.
6. I thought that in the data files I was reading the time was stored in one or two doubles. Sometimes with a timestamp+offset protocol that would have to be converted to TAI JD.

**Comment by NiklasPhabian** [comment]
My main concern is what the preferred interface between pystare and STARE should be for temporal. It would seem to me that we really just want to pass two-part JDs and do all conversions (e.g. from datetime, pyerfa, datetime64, iso strings) in pystare via astropy. 

> Also, the most common use case I've had so far is (A) Generate the TID, then (B) set the resolutions afterwards. Type is assumed 1 for the time being (others not implemented).

Perfect. I will wrap those two functions then and use it as my canonical entry point ... unless the following is simpler:

> Historically, the 2-doubles calls map to ERFA calls and don't touch resolution or type, i.e. they are low-level constructor aids. I'll try to add res/res/type to the signature.

Regarding JD and datetime:

> I don't think users working in double should have to go through an extra encoding to get a tid.

> Since this is Python-world, I imagine most temporal data is going in via datetime.

Exactly. The ```from_jd(jd1, jd2, fres, bres, type, scale)``` is the default/low_level interface. Additionally, we write wrappers that convert from datetime, ISO string, etc to two-part JDs (via astropy) and then call ```from_jd()```. 

> What do you mean by separate functions? You mean to not have them in the STARE API? JD only? POSIX only?

I mean separate pystare functions.

**Comment by michaelleerilee** [comment]
This line of thinking seems fine. See if the new STARE 1.2.0 routines help.

What does "scale" do in from_jd?

**Comment by NiklasPhabian** [comment]
> What does "scale" do in from_jd?

I took the word 'scale' from [astropy.time](https://docs.astropy.org/en/stable/time/index.html). Pyerfa also has the scale notion; but only for UTC. e.g. in [d2dtf()](https://pyerfa.readthedocs.io/en/latest/api/erfa.d2dtf.html#erfa.d2dtf) and  the inverse [dtf2d()](https://pyerfa.readthedocs.io/en/latest/api/erfa.dtf2d.html#erfa.dtf2d)

"Specific emphasis is placed on supporting time scales (e.g., UTC, TAI, UT1, TDB) and time representations (e.g., JD, MJD, ISO 8601) "

**Comment by michaelleerilee** [comment]
It's a weird scale that has leap seconds.

**Comment by NiklasPhabian** [comment]
Oh! I only just now saw this
https://github.com/SpatioTemporal/pystare/issues/37#issuecomment-903189273_
OK. This makes it all straightforward.
