### ISSUE TITLE
do we need a functions to/from_utc_iso_strings() 

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#44]
we have to/from_tai_iso_strings(); do we need according functions for UTC?

**Comment by michaelleerilee** [comment]
Maybe UTC users would prefer using datetime objects?

**Comment by NiklasPhabian** [comment]
This is solved. 
We have ```from_iso_strings()``` which allows us to specify the scale as 'tai' or 'utc'.
To produce a string, we have ```to_stare_timestring()```, which again allows us to specify the scale.
We don't have a method to produce straight ISO time strings (w/o the STARE resolution info). But the users can go through JDs and astropy for such gymnastics.
