### ISSUE TITLE
from_tai_iso_strings() modifies inputs

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#45]
the function modifies its input in place to a STARE time string.

```python
time_string = ['2021-08-09T15:05:29.243']
pystare.from_tai_iso_strings(time_string)
print(time_string)
['2021-08-09T15:05:29.243 (48 48) (1)']
```

**Comment by michaelleerilee** [comment]
Regarding these strings, they should be considered "STARE" strings, based on (TAI) and ISO format. If it's a STARE time string then it should have the resolution and type information, but when presented with just the ISO part we assume the finest resolution and type=1.

**Comment by michaelleerilee** [comment]
Easy to make functional if needed.

**Comment by NiklasPhabian** [comment]
> Regarding these strings, they should be considered "STARE" strings, based on (TAI) and ISO format. If it's a STARE time string then it should have the resolution and type information, but when presented with just the ISO part we assume the finest resolution and type=1.

Agreed!

**Comment by NiklasPhabian** [comment]
> Easy to make functional if needed.

Yes. Needed. To be clear from_tai_iso_strings() returns the tiv, but *ALSO* modifies the input. IMO, a python API user won't (ever) expect their inputs to be modified by a function. 

Quick-fixed with a shallow copy.

**Comment by NiklasPhabian** [comment]
should be closed with https://github.com/SpatioTemporal/pystare/pull/37
