### ISSUE TITLE
should from_JulianTAI/UTC() include resolutions and type as parameters?

### ISSUE THREAD

**Issue by NiklasPhabian** [SpatioTemporal/pystare#47]
this might just be misunderstanding something, but shouldn't ```from_JulianTAI()``` and ```from_JulianUTC()``` also take resolutions and type as a parameter? I.e.

```python
def from_julian_tai(d1, d2, res_forward=48, res_backwards=48, type=1):
    pass
```

If this is not implemented in the STARE library yet, we should leave those defaults as placeholders at least

**Comment by michaelleerilee** [comment]
We might consider these added in STARE vs. 1.2.0.

From TemporalIndex.h.
```
        TemporalIndex& fromJulianUTC ( double  utc1, double  utc2, int forward_resolution=48, int reverse_resolution=48, int type=1  );

	TemporalIndex& fromJulianTAI ( double  d1, double  d2, int forward_resolution=48, int reverse_resolution=48, int type=1  );
```

From STARE.h (which doesn't respect the jd1,jd2 convention, coercing to jd1+jd2).
```
	double toJulianDayTAI();
	TemporalIndex& fromJulianDayTAI(double d, int forward_resolution, int reverse_resolution, int type);
```
