### ISSUE TITLE
Whither to_utc_approximate?

### ISSUE THREAD

**Issue by michaelleerilee** [SpatioTemporal/pystare#69]
AttributeError: module 'pystare' has no attribute 'to_utc_approximate'?

**Comment by michaelleerilee** [comment]
It's now core._to_utc_approximate.

So what's the right way to get a utc datetime from a temporal id?

**Comment by NiklasPhabian** [comment]
for now, we have [to_stare_timestring](https://pystare.readthedocs.io/en/latest/reference/temporal.html)

Other than that, we could do 
1. [to_julian_date](https://pystare.readthedocs.io/en/latest/reference/api2/pystare.temporal.to_julian_date.html#pystare.temporal.to_julian_date) and then format with [astropy](
https://docs.astropy.org/en/stable/time/index.html)
2. [to_ms_since_epoch_utc](https://pystare.readthedocs.io/en/latest/reference/api2/pystare.temporal.to_ms_since_epoch_utc.html#pystare.temporal.to_ms_since_epoch_utc) and then format with [datetime](https://docs.python.org/3/library/datetime.html)

Full roundtrips:
```python
import pystare
import astropy.time
import datetime

# Create the TIVs
times = ['2021-09-03', '2021-07-17 11:16']
times = astropy.time.Time(series, scale='utc', format='datetime64')
tivs = pystare.from_julian_date(times.jd1, times.jd2, scale='utc', forward_res=48, reverse_res=48)

# Back via JD
jd = pystare.to_julian_date(tivs, scale='utc')
times = astropy.time.Time(val=jd[0], val2=jd[1], format='jd')
times.to_datetime()

# Back via MS
mss = pystare.to_ms_since_epoch_utc(tivs)
dts = [datetime.datetime.utcfromtimestamp(ms/1000) for ms in mss]
[dt.isoformat() for dt in dts]
```

I shall add those to the documentation
```
